### PR TITLE
Add film

### PR DESCRIPTION
**Pull request by CLucas96**
- Add Film Form Created. 
- Edit Film Form Created.
- Delete Film Form Created 
- Film Details View Created With Links to Add/Edit/Delete Forms
- Home Page Modified for ease of access. 
- Add Film Added to Nav Bar.  Only Admin Users can see the option

### CODE REVIEW

**Comment by oirholt** [comment]
- Errors: Various and many
- Bugs: 1
- Suggestions: 1

The following functionality is attempted: **Add Films**; **Edit Films**; and **Views restricted-by-role**. Various Controllers, Models, and Views have been added: the **controller**, _FilmsController.cs_; the **models**, _Film.cs, FilmContext.cs, FilmDataInitialiser.cs_; the **views**, _Create.cshtml, Delete.cshtml, Details.cshtml, Edit.cshtml, and Index.cshtml_. Present and correct: Models' virtual attributes, seed-data, and custom database-initialisation. Present and correct: Controller's Add, Edit, and Delete ActionResults. Present and correct: Partial layout, _layout.cshtml_,; its if statement displays the _Add Director_ (_Create.cshtml_) ActionLink exclusively to Administrators. Standard users' and Administrators' homepages `href `the Films list (`Model.Items`, _Index.cshtml_), passed via `ViewBag`. Via `ViewBag`, homepages now link to the films index. 

Upon cloning this branch, _AddFilm_, umpteen _Error List_ errors, warnings, and messages displayed. .NET-styled markup, (`//`) --comments attempted within  XML documents (Web.configs), as well as Razor Views (.cshtml) -- introduced illegal syntax errors. After deleting illegal markup, restoring the SQL database (.MDF, .LDF), and repairing localhost incompatibilities (NuGet packages, dependencies, references, etc.), errors were resolved.

Testing subsequently took place. Adding, editing, and listing films (_Model.Items_) works without issue. Commendably, a reusable partial view, __Layout.cshtml_, is employed. Despite this, it is sorely lacking` IsInRole` if statements which determine the current user's role. Consequently, standard users (and, even, logged-out, membership-less users) can add and edit films. This author has follow-up commit with the following code:

_(Film, Details.cshtml)_:

        _
        @if (User.IsInRole("Administrator"))
        {
            @Html.ActionLink("Edit", "Edit", new { id = Model.FilmId })
        }_

_(Film, Index.cshtml)_:

```
                <!-- Displays the edit details link if the user is an administrator -->
                @if (User.IsInRole("Administrator"))
                    {
                        @Html.ActionLink("Edit", "Edit", new { id = item.FilmId })
                    }
```


_(Layout.cshtml)_:

```
                     @if (User.IsInRole("Administrator"))
                     {
                         <li>@Html.ActionLink("Administration", "Index", "Admin")</li>
                        <li>@Html.ActionLink("Add Film", "Create", "Films")</li>
                     }
```

Altogether, models, views, and controllers achieve adding films, viewing film details, editing film details, and listing film (`Model.Items`). Sans delete, reviews, and genre tags, all necessary film-related functionality (illustrated by use-case documentation, outlined by client requirements) is realised,. Through this author's testing, functionality proves complete, well-implemented, and functional, excepting bugs noted above.

In follow-up commits, bugs have been resolved. Standard users can hitherto no longer add and edit films. The code with which this was solved has been pushed to the branch, _AddFilm_. Consequently, review this code before merging branches. Due to local host incompatibilites (dependecies, references, NuGet packages), reviews requested from all developers: Christopher (CLucas98), Joseph (JEngel98), Marek (marekiwo), Matthew (MattyJP), Nicolle (NicolleL93). Available upon request: .MDF to facilitate testing.

**Comment by MattyJP** [comment]
Developer confirming that functionality is present. No errors present during functionality testing.

**Comment by JEngel98** [comment]
I can confirm that this branch works fine on my end so it ready to be merged.

**Comment by marekiwo** [comment]
Tested and I am able to confirm that it is fully operation and I have not encountered any errors during my testing.

**Comment by oirholt** [comment]
All developers & system analysts have tested the fixed code, no longer experience localhost errors, and approve my merging. Due to localhost branch conflicts, AddFilm's changes, which every developer & analyst here tested and approved, have been merged directly into the Master branch (see: commits). Therefore, with AddFilm now merged into Master elsewhere, this pull request can now be closed.

**Pull request closed without merging**
